version: '3.11'
services:
  ollama:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/ollama/ollama:latest
    restart: always
    volumes:
      - ~/.ollama:/root/.ollama
    environment:
      # 代理加速模型拉取（host.docker.internal 指向宿主机，需宿主机开代理监听7890端口）
      # 如果宿主机没有代理，将以下两行注释掉即可
      - HTTPS_PROXY=http://host.docker.internal:7890
      - HTTP_PROXY=http://host.docker.internal:7890
      # HuggingFace 镜像加速（ollama部分模型从HF拉取）
      - HF_ENDPOINT=https://hf-mirror.com
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  chatchat:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - ollama
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - OLLAMA_MODELS=${OLLAMA_MODELS}
      - OLLAMA_HOST=ollama
    #volumes:
    #  - ../data:/root/MDT/mdt_data
    #  - ../libs/chatchat-server:/root/MDT/libs/chatchat-server
    ports:
      - "7861:7861"
      - "8501:8501"  # WebUI端口
      - "4040:4040"  # ngrok web界面
